# .github/workflows/deploy.yml

name: Deploy Lightdash to AWS ECS

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

# These are the environment variables for the workflow
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: billing-calculator-lightdash
  ECS_CLUSTER_NAME: billing-calculator-lightdash-cluster
  ECS_SERVICE_NAME: billing-calculator-lightdash-task-service-expd9khb

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: "Configure AWS Credentials" Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Force new deployment on ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.ECS_SERVICE_NAME }} --force-new-deployment